### ISSUE TITLE
NHHall does not compile on Fedora 43 / g++ 15.2.1

### ISSUE THREAD

**Issue by znmeb** [ccrma/chugins#106]
```
$ g++ --version
g++ (GCC) 15.2.1 20260123 (Red Hat 15.2.1-7)
Copyright (C) 2025 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

This is what happens - all the other default ChuGins compile.

```
make[1]: Entering directory '/tmp/chugins-chuck-1.5.5.7/NHHall'
g++ -D__LINUX_ALSA__ -D__PLATFORM_LINUX__ -I../chuck/include/ -fPIC --std=c++11 -O3 -Werror -c -o NHHall.o NHHall.cpp
In file included from NHHall.cpp:1:
nh_hall.hpp:260:22: error: ‘uint32_t’ has not been declared
  260 |     inline void seed(uint32_t seed) {
      |                      ^~~~~~~~
nh_hall.hpp:165:1: note: ‘uint32_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
  164 | #include <cmath> // cosf/sinf
  +++ |+#include <cstdint>
  165 | 
nh_hall.hpp:264:12: error: ‘uint16_t’ does not name a type
  264 |     inline uint16_t run_lcg(void) {
      |            ^~~~~~~~
nh_hall.hpp:264:12: note: ‘uint16_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
nh_hall.hpp:301:5: error: ‘uint32_t’ does not name a type
  301 |     uint32_t m_lcg_state = 1;
      |     ^~~~~~~~
nh_hall.hpp:301:5: note: ‘uint32_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
nh_hall.hpp: In member function ‘void nh_ugens::RandomLFO::seed(int)’:
nh_hall.hpp:261:9: error: ‘m_lcg_state’ was not declared in this scope
  261 |         m_lcg_state = seed;
      |         ^~~~~~~~~~~
nh_hall.hpp: In member function ‘nh_ugens::Stereo nh_ugens::RandomLFO::process()’:
nh_hall.hpp:286:31: error: ‘run_lcg’ was not declared in this scope
  286 |             m_timeout = (int)(run_lcg() * 0.1f / m_frequency * m_sample_rate / 48000.0f);
      |                               ^~~~~~~
nh_hall.hpp: At global scope:
nh_hall.hpp:711:22: error: ‘uint32_t’ has not been declared [-Wtemplate-body]
  711 |     inline void seed(uint32_t seed) {
      |                      ^~~~~~~~
nh_hall.hpp:711:22: note: ‘uint32_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
make[1]: *** [makefile:105: NHHall.o] Error 1
make[1]: Target 'linux' not remade because of errors.
make[1]: Leaving directory '/tmp/chugins-chuck-1.5.5.7/NHHall'
make: *** [makefile:45: NHHall/NHHall.chug] Error 2
```

Here's the log of the whole ChuGins compile:

[chugins-compile.log.gz](https://github.com/user-attachments/files/26064227/chugins-compile.log.gz)
